//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScraperFront.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public long id { get; set; }
        public string Ticker { get; set; }
        public string Stock_Price { get; set; }
        public string Price_Change { get; set; }
        public string Price_Percent_Change { get; set; }
        public string Trade_Volume { get; set; }
        public string Market_Cap { get; set; }
        public System.DateTime ScrapeDateTime { get; set; }
    
        public virtual Stock Stocks1 { get; set; }
        public virtual Stock Stock1 { get; set; }
    }
}
